//! Embedded C++ solution template.
//!
//! The template is compiled into the binary (`const &str`), so the helper never
//! needs template files on disk. `{{PROBLEM_NAME}}` and `{{URL}}` are replaced
//! when a workspace is generated.

/// Placeholder for the problem name inside [`CPP_TEMPLATE`].
pub const PLACEHOLDER_NAME: &str = "{{PROBLEM_NAME}}";
/// Placeholder for the problem URL inside [`CPP_TEMPLATE`].
pub const PLACEHOLDER_URL: &str = "{{URL}}";

/// Default competitive-programming skeleton written to `main.cpp`.
pub const CPP_TEMPLATE: &str = r#"// {{PROBLEM_NAME}}
// {{URL}}
// Generated by ZedComp (helper). Write your solution below.
#include <bits/stdc++.h>
using namespace std;

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    return 0;
}
"#;

/// Render the C++ template with the problem name / URL substituted.
///
/// Newlines are stripped from the substitutions so the leading `//` comment
/// block cannot be broken by a hostile (or just multi-line) problem name.
pub fn render_cpp(problem_name: &str, url: &str) -> String {
    let clean_name = single_line(problem_name, "problem");
    let clean_url = single_line(url, "");
    CPP_TEMPLATE
        .replace(PLACEHOLDER_NAME, &clean_name)
        .replace(PLACEHOLDER_URL, &clean_url)
}

fn single_line(value: &str, fallback: &str) -> String {
    let joined: String = value
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ");
    if joined.is_empty() {
        fallback.to_string()
    } else {
        joined
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn template_keeps_bits_header_and_ios_tweaks() {
        assert!(CPP_TEMPLATE.contains("#include <bits/stdc++.h>"));
        assert!(CPP_TEMPLATE.contains("ios::sync_with_stdio(false)"));
        assert!(CPP_TEMPLATE.contains("cin.tie(nullptr)"));
    }

    #[test]
    fn render_replaces_both_placeholders() {
        let out = render_cpp("A. String Task", "https://codeforces.com/problemset/problem/118/A");
        assert!(out.contains("// A. String Task"));
        assert!(out.contains("// https://codeforces.com/problemset/problem/118/A"));
        assert!(!out.contains(PLACEHOLDER_NAME));
        assert!(!out.contains(PLACEHOLDER_URL));
        // placeholders must be substituted in the header comment only; the rest
        // of the template is byte-identical.
        assert!(out.ends_with("    return 0;\n}\n"));
    }

    #[test]
    fn render_flattens_multiline_names() {
        let out = render_cpp("A. Weird\nName", "https://example.com/x");
        assert!(out.contains("// A. Weird Name\n"));
        assert!(!out.contains("Weird\nName"));
    }
}
